# Generated by Django 2.2 on 2022-06-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0006_auto_20220603_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
