# Generated by Django 2.2 on 2022-07-04 17:09

from django.db import migrations


def user_to_profile(apps, schema_editor):
    User = apps.get_model('coplate', 'User')
    Profile = apps.get_model('coplate', 'Profile')

    for user in User.objects.all():
        Profile.objects.create(
            nickname = user.nickname,
            profile_pic = user.profile_pic,
            intro = user.intro,
            user = user,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0007_profile'),
    ]

    operations = [
        migrations.RunPython(user_to_profile),
    ]
