# Generated by Django 2.2 on 2022-07-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0008_migrate_profle_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
